spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


  springdoc:
    swagger-ui:
      enabled: false
    api-docs:
      enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.project.ordersystemapi: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.hibernate: WARN

