spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_system
    driver-class-name: org.postgresql.Driver
    username: sa
    password: root123
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
